In [1]:
import numpy as np
import pandas as pd
salaries = pd.read_csv("Salaries.csv")

/Users/leeranfarin/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [21]:
columns = salaries.columns[3:7];
columns

Index(['BasePay', 'OvertimePay', 'OtherPay', 'Benefits'], dtype='object')

In [25]:
salaries[columns] = salaries[columns].apply(pd.to_numeric, errors='coerce')
salaries

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency Status  
0         NaN  San Francisco    NaN  
1         NaN  San Francisco    NaN  
2         NaN  San Francisco    NaN  
3         NaN  San Francisco    NaN  
4         NaN  San Francisco    NaN  
...       ...            ...    ...  
148649    NaN  San Francisco     PT  
148650    NaN  San Francisco    NaN  
148651    NaN  San Francisco    NaN  
148652    NaN  San Francisco    NaN  
148653    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [26]:
salaries.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object

In [38]:
# gets details of all info
salaries.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0  
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN  
std     15402.215858   50517.005274      62793.533483       1.117538    NaN  
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN  
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN  
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN  
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN  
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN

In [44]:
len(list(salaries['JobTitle'].unique()))

2159

In [46]:
#return number of unique items in the data column
salaries['JobTitle'].nunique()

2159

In [55]:

salaries.groupby('JobTitle')['BasePay'].count()

JobTitle
ACCOUNT CLERK                                      83
ACCOUNTANT                                          5
ACCOUNTANT INTERN                                  48
ACPO,JuvP, Juv Prob (SFERS)                         1
ACUPUNCTURIST                                       1
                                                 ... 
X-RAY LABORATORY AIDE                              26
X-Ray Laboratory Aide                             100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS      1
Youth Comm Advisor                                  4
ZOO CURATOR                                         1
Name: BasePay, Length: 2159, dtype: int64

In [61]:
#average of all benefites for each job title
salaries.groupby("JobTitle")['Benefits'].mean()

JobTitle
ACCOUNT CLERK                                            NaN
ACCOUNTANT                                               NaN
ACCOUNTANT INTERN                                        NaN
ACPO,JuvP, Juv Prob (SFERS)                       17975.5900
ACUPUNCTURIST                                            NaN
                                                     ...    
X-RAY LABORATORY AIDE                                    NaN
X-Ray Laboratory Aide                             18697.1805
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS           NaN
Youth Comm Advisor                                18704.2425
ZOO CURATOR                                              NaN
Name: Benefits, Length: 2159, dtype: float64

In [103]:
maxsalaries = salaries.groupby("JobTitle")['TotalPay'].max()
maxsalaries.max() - maxsalaries.min()

567595.43

In [104]:
# maxsalaries.min()
maxsalaries[maxsalaries <=0]

0.0

In [106]:
salaries[salaries['JobTitle']]

KeyError: "None of [Index(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',\n       'CAPTAIN III (POLICE DEPARTMENT)', 'CAPTAIN III (POLICE DEPARTMENT)',\n       'WIRE ROPE CABLE MAINTENANCE MECHANIC',\n       'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',\n       'ASSISTANT DEPUTY CHIEF II', 'BATTALION CHIEF, (FIRE DEPARTMENT)',\n       'DEPUTY DIRECTOR OF INVESTMENTS', 'BATTALION CHIEF, (FIRE DEPARTMENT)',\n       'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',\n       ...\n       'Stationary Eng, Sewage Plant', 'Human Services Technician',\n       'Not provided', 'Communications Dispatcher 2', 'Custodian', 'Custodian',\n       'Not provided', 'Not provided', 'Not provided',\n       'Counselor, Log Cabin Ranch'],\n      dtype='object', length=148654)] are in the [columns]"

In [148]:
arr = np.array([1,2,3])
arr[0]

1

In [113]:
arr = np.array([[ 1,  5,  9, 13], [17, 21, 25, 29],[33, 37, 41, 45]])
arr

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [120]:
print(arr[1:, 1:3])

[[21 25]
 [37 41]]


In [124]:
arr1 = np.random.randint(1, high=100, size=25)

In [128]:
avg = arr1.mean()
median = np.median(arr1)

In [134]:
print(avg)
print(median)

43.04
38.0


In [142]:
if avg > median:
    print(avg)

43.04


In [145]:
abs(30-38)

8

In [150]:
arr[arr > 1]

array([2, 3])

In [160]:
arr = np.random.randint(1, high=100, size=25)

print(arr)

mean = arr.mean()

print(mean)

median = np.median(arr)

print(median)

difference = median - mean;

if abs(difference) <= 3:
    print(arr[arr > 25])
else :
    print( arr[arr > 50])

[77 28 45 71 25  2 56 42  5 83 72 94 99 75  4 90 63 77 13 92 48 22 67 18
 51]
52.76
56.0
[77 71 56 83 72 94 99 75 90 63 77 92 67 51]


In [167]:
salaries = salaries.reset_index()

In [171]:
salaries[0]

KeyError: 0

In [173]:
salaries

index      Id       EmployeeName  \
0            0       1     NATHANIEL FORD   
1            1       2       GARY JIMENEZ   
2            2       3     ALBERT PARDINI   
3            3       4  CHRISTOPHER CHONG   
4            4       5    PATRICK GARDNER   
...        ...     ...                ...   
148649  148649  148650      Roy I Tillery   
148650  148650  148651       Not provided   
148651  148651  148652       Not provided   
148652  148652  148653       Not provided   
148653  148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency Status  
0         NaN  San Francisco    NaN  
1         NaN  San Francisco    NaN  
2         NaN  San Francisco    NaN  
3         NaN  San Francisco    NaN  
4         NaN  San Francisco    NaN  
...       ...            ...    ...  
148649    NaN  San Francisco     PT  
148650    NaN  San Francisco    NaN  
148651    NaN  San Francisco    NaN  
148652    NaN  San Francisco    NaN  
148653    NaN  San Francisco     PT  

[148654 rows x 14 columns]

In [186]:
df = pd.read_csv("titanic_clean.csv")

In [183]:
len(df.values)

887

In [184]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='object')

In [185]:
df['Survived'].sum()

342

In [195]:
arr = np.random.randint(1, high=100, size=25)
print(arr)
mean = arr.mean()
print(mean)
median = np.median(arr)
print(median)
difference = median - mean;
if abs(difference) <= 3:
    print(arr[arr > 25])
else :
    print(arr[arr > 50])

[68 10  4 67 23 95 88 98 76 77 14 63 50 73 81 81 41  8 52 92 87 54 55 24
 40]
56.84
63.0
[68 67 95 88 98 76 77 63 50 73 81 81 41 52 92 87 54 55 40]


In [203]:
salaries

index      Id       EmployeeName  \
0            0       1     NATHANIEL FORD   
1            1       2       GARY JIMENEZ   
2            2       3     ALBERT PARDINI   
3            3       4  CHRISTOPHER CHONG   
4            4       5    PATRICK GARDNER   
...        ...     ...                ...   
148649  148649  148650      Roy I Tillery   
148650  148650  148651       Not provided   
148651  148651  148652       Not provided   
148652  148652  148653       Not provided   
148653  148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency Status  
0         NaN  San Francisco    NaN  
1         NaN  San Francisco    NaN  
2         NaN  San Francisco    NaN  
3         NaN  San Francisco    NaN  
4         NaN  San Francisco    NaN  
...       ...            ...    ...  
148649    NaN  San Francisco     PT  
148650    NaN  San Francisco    NaN  
148651    NaN  San Francisco    NaN  
148652    NaN  San Francisco    NaN  
148653    NaN  San Francisco     PT  

[148654 rows x 14 columns]

In [207]:
df.loc[887] = []

ValueError: cannot set a row with mismatched columns