In [2]:
import numpy as np

In [8]:
x1 = np.random.randint(5, size=(3,6))
x1

array([[2, 2, 4, 1, 2, 4],
       [3, 2, 2, 2, 1, 0],
       [3, 1, 4, 2, 4, 1]])

In [10]:
x1.transpose()

array([[2, 3, 3],
       [2, 2, 1],
       [4, 2, 4],
       [1, 2, 2],
       [2, 1, 4],
       [4, 0, 1]])

In [11]:
x1.transpose().sum(axis = 1)

array([ 8,  5, 10,  5,  7,  5])

In [12]:
x1.sum(axis = 1)

array([15, 10, 15])

In [15]:
from numpy import random

In [19]:
x2 = random.randint(25, size=(4,6))
x2

array([[ 5, 23,  4, 19, 16,  6],
       [ 8, 19, 19, 13, 12,  7],
       [ 8, 20, 23,  4, 21, 16],
       [10,  1, 18, 20,  1, 14]])

In [22]:
x2.max(axis=0) > 15

array([False,  True,  True,  True,  True,  True])

In [23]:
x2.max(axis=0)

array([10, 23, 23, 20, 21, 16])

In [24]:
x2.max(axis=1)

array([23, 19, 23, 20])

In [34]:
x3 = random.randint(20, size = 4)
x3

array([12,  6, 13,  8])

In [41]:
#gets you back a array of the specific items in the index
ind  = [1,3]
x3[ind]

array([6, 8])

In [36]:
np.all(x3 < 10)

False

In [37]:
#checks if any all items are true
np.all(x3 > 5)


True

In [39]:
#counts all non zero items in a lsit
np.count_nonzero(x3)

4

In [43]:
x4 = random.randint(10, size = 10)
x4

array([3, 9, 3, 9, 6, 7, 4, 2, 3, 4])

In [44]:
np.sort(x4)

array([2, 3, 3, 3, 4, 4, 6, 7, 9, 9])

In [47]:
sorted = np.sort(x4, kind='mergesort')

In [48]:
sorted

array([2, 3, 3, 3, 4, 4, 6, 7, 9, 9])

In [49]:
x4

array([3, 9, 3, 9, 6, 7, 4, 2, 3, 4])

In [50]:
sorted[0] = 5

In [51]:
x4

array([3, 9, 3, 9, 6, 7, 4, 2, 3, 4])

In [52]:
sorted

array([5, 3, 3, 3, 4, 4, 6, 7, 9, 9])

In [53]:
x4.sort()

In [54]:
x4

array([2, 3, 3, 3, 4, 4, 6, 7, 9, 9])

In [62]:
x5 = [6,1,2,3,4,5]

In [59]:
np_x5 = np.sort(x5)
np_x5

array([1, 2, 3, 4, 5, 6])

# Pandas

In [65]:
import pandas as pd

In [69]:
# how to read data from a csv file
df = pd.read_csv("iris.csv")

In [72]:
#pandas dataframe
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [75]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [79]:
#gets column
df['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [81]:
#each column is a series
type(df['SepalLengthCm'])

pandas.core.series.Series

In [84]:
#gives you the beginning N number lines
df.head(3)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [92]:
#returns values of all the columns in a nparray
vals = df['SepalLengthCm'].values


In [93]:
vals.max()

7.9