In [3]:
seq = ['a', 'b', 'c', 'd']

In [4]:
#print out all elements in list seq

for item in seq:
    print(item)

a
b
c
d


In [11]:
courses = [("CSC245", 4), ("CSC438", 5)]

In [13]:
#gets each element from tuple in the list and prints
for a, b in courses:
    print(a + " : " + str(b))

CSC245 : 4
CSC438 : 5


### NumPy has a special type called ndarray (N Dimensional Array), taking the inefficient memory of Python, and uses c++ storage for more efficient data storage.

In [15]:
# imports numpy
import numpy as np

In [17]:
#documentation of numpy
np?

In [19]:
np.random.seed(0)

# we can destructure methods from imports by doing
from numpy import random

In [26]:
#shift-tab will show documentation of a method/function
x1 = random.randint(20, size = 6)
x1

array([14,  7,  0,  1,  9,  0])

In [28]:
type(x1)

numpy.ndarray

In [35]:
#how many dimensions does this array have?
print(x1.ndim)
print(x1.shape)
print(x1.size)

1
(6,)
6


In [40]:
#x2 will be an array of arrays in the size[row = 3 - 1][column = 4 - 1]
x2 = random.randint(10, size = (3,4))
x2

array([[6, 7, 2, 0],
       [3, 5, 9, 4],
       [4, 6, 4, 4]])

In [41]:
print(x2.ndim)
print(x2.shape)
print(x2.size)

2
(3, 4)
12


In [43]:
x2.dtype

dtype('int64')

In [50]:
#slicing NumPy arrays
x1
x1[1:]

array([7, 0, 1, 9, 0])

In [56]:
x2[1:,2:]

array([[9, 4],
       [4, 4]])

In [61]:
x3 = random.randint(10, size=(5, 7))
x3

array([[3, 2, 3, 6, 3, 6, 5],
       [7, 0, 8, 4, 6, 5, 8],
       [2, 3, 9, 7, 5, 3, 4],
       [5, 3, 3, 7, 9, 9, 9],
       [7, 3, 2, 3, 9, 7, 7]])

In [68]:
x3slice = x3[1:3, 2:5]
x3slice

array([[8, 4, 6],
       [9, 7, 5]])

In [73]:
#slices takes a VIEW of the actual array, it does not copy
x3slice[1,1] = -100
x3slice

array([[   8,    4,    6],
       [   9, -100,    5]])

In [76]:
#the original array changed, by changing x3slice
x3

array([[   3,    2,    3,    6,    3,    6,    5],
       [   7,    0,    8,    4,    6,    5,    8],
       [   2,    3,    9, -100,    5,    3,    4],
       [   5,    3,    3,    7,    9,    9,    9],
       [   7,    3,    2,    3,    9,    7,    7]])

In [81]:
#to create a copy of the array from the original
x3piece = x3[1:3, 2:5].copy()
x3piece[1,1] = 1
x3piece

array([[8, 4, 6],
       [9, 1, 5]])

In [84]:
#altering x3piece, did NOT alter x3 this time
x3

array([[   3,    2,    3,    6,    3,    6,    5],
       [   7,    0,    8,    4,    6,    5,    8],
       [   2,    3,    9, -100,    5,    3,    4],
       [   5,    3,    3,    7,    9,    9,    9],
       [   7,    3,    2,    3,    9,    7,    7]])

In [90]:
onedarray = random.randint(5,26, size = 15)
onedarray

array([15, 19, 25, 23,  9,  8, 24, 12, 13, 18, 10,  5, 13, 20, 20])

In [93]:
# creates a range using numpy
nums = np.arange(20,30)
nums

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [95]:
#concatenating using numpy
np.concatenate((nums, x1))

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 14,  7,  0,  1,  9,  0])

In [96]:
x2

array([[6, 7, 2, 0],
       [3, 5, 9, 4],
       [4, 6, 4, 4]])

In [102]:
x5 = random.randint(10, size = 4)
x5

array([8, 4, 4, 1])

In [105]:
#arrays need to be the same dimensions to concatenate
#default = axis = 0, adding new rows
np.concatenate((x5, x2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [109]:
x6 = random.randint(10, size = (3,8))

In [112]:
#axis = 1 will concatenate adding new columns
np.concatenate((x6, x2), axis=1)

array([[1, 4, 5, 0, 3, 1, 4, 4, 6, 7, 2, 0],
       [4, 0, 0, 8, 4, 6, 9, 3, 3, 5, 9, 4],
       [3, 2, 1, 2, 1, 3, 4, 1, 4, 6, 4, 4]])

In [129]:
##x1.sort()
#sorted
x1

array([ 0,  0,  1,  7,  9, 14])

In [115]:
x1.sum()

31

In [128]:
x1.mean()

5.166666666666667

In [127]:
# x1 ^ 2
x1 ** 2

array([  0,   0,   1,  49,  81, 196])

In [118]:
x1.min()

0

In [120]:
#or np.max(x1)
x1.max()

14

In [122]:
np.median(x1)

4.0

In [130]:
x2

array([[6, 7, 2, 0],
       [3, 5, 9, 4],
       [4, 6, 4, 4]])

In [146]:
#sums up the colums
arr = np.sum(x2, axis=0)
arr

array([13, 18, 15,  8])

In [134]:
#sums up the rows
np.sum(x2, axis=1)

array([15, 21, 18])

In [136]:
x6

array([[1, 4, 5, 0, 3, 1, 4, 4],
       [4, 0, 0, 8, 4, 6, 9, 3],
       [3, 2, 1, 2, 1, 3, 4, 1]])

In [138]:
x6[1].min()

0

In [142]:
#largest row sum
np.max(np.sum(x6, axis=1))

34

In [149]:
# gives me booleans for a condition
print(arr)
arr > 10

[13 18 15  8]


array([ True,  True,  True, False])

In [155]:
#slicing the array for certain values
arr[arr > 10]

array([13, 18, 15])

In [160]:
# length of a certain slice
len(arr[arr > 10])

3